def on_button_pressed_a():
    item.change(LedSpriteProperty.Y, -1)
input.on_button_pressed(Button.A, on_button_pressed_a)

def on_button_pressed_b():
    item.change(LedSpriteProperty.Y, 1)
input.on_button_pressed(Button.B, on_button_pressed_b)

enemy_item_4: game.LedSprite = None
enemy_item_3: game.LedSprite = None
enemy_item_2: game.LedSprite = None
enemy_item_1: game.LedSprite = None
item: game.LedSprite = None
game.set_life(3)
item = game.create_sprite(0, 0)
item.turn(Direction.RIGHT, 90)
basic.show_string("LVL1")
for index in range(15):
    enemy_item_1 = game.create_sprite(5, randint(0, 5))
    basic.pause(250)
    enemy_item_1.change(LedSpriteProperty.X, -1)
    basic.pause(250)
    enemy_item_1.change(LedSpriteProperty.X, -1)
    basic.pause(250)
    enemy_item_1.change(LedSpriteProperty.X, -1)
    basic.pause(250)
    enemy_item_1.change(LedSpriteProperty.X, -1)
    basic.pause(250)
    enemy_item_1.delete()
basic.show_string("LVL2")
for index2 in range(15):
    enemy_item_1 = game.create_sprite(5, randint(0, 5))
    enemy_item_2 = game.create_sprite(5, randint(0, 5))
    basic.pause(250)
    enemy_item_1.change(LedSpriteProperty.X, -1)
    enemy_item_2.change(LedSpriteProperty.X, -1)
    basic.pause(250)
    enemy_item_1.change(LedSpriteProperty.X, -1)
    enemy_item_2.change(LedSpriteProperty.X, -1)
    basic.pause(250)
    enemy_item_1.change(LedSpriteProperty.X, -1)
    enemy_item_2.change(LedSpriteProperty.X, -1)
    basic.pause(250)
    enemy_item_1.change(LedSpriteProperty.X, -1)
    enemy_item_2.change(LedSpriteProperty.X, -1)
    basic.pause(250)
    enemy_item_1.delete()
    enemy_item_2.delete()
basic.show_string("LVL3")
for index3 in range(15):
    enemy_item_1 = game.create_sprite(5, randint(0, 5))
    enemy_item_2 = game.create_sprite(5, randint(0, 5))
    enemy_item_3 = game.create_sprite(5, randint(0, 5))
    basic.pause(250)
    enemy_item_1.change(LedSpriteProperty.X, -1)
    enemy_item_2.change(LedSpriteProperty.X, -1)
    enemy_item_3.change(LedSpriteProperty.X, -1)
    basic.pause(250)
    enemy_item_1.change(LedSpriteProperty.X, -1)
    enemy_item_2.change(LedSpriteProperty.X, -1)
    enemy_item_3.change(LedSpriteProperty.X, -1)
    basic.pause(250)
    enemy_item_1.change(LedSpriteProperty.X, -1)
    enemy_item_2.change(LedSpriteProperty.X, -1)
    enemy_item_3.change(LedSpriteProperty.X, -1)
    basic.pause(250)
    enemy_item_1.change(LedSpriteProperty.X, -1)
    enemy_item_2.change(LedSpriteProperty.X, -1)
    enemy_item_3.change(LedSpriteProperty.X, -1)
    basic.pause(250)
    enemy_item_1.delete()
    enemy_item_2.delete()
    enemy_item_3.delete()
basic.show_string("LVL4")
for index4 in range(15):
    enemy_item_1 = game.create_sprite(5, randint(0, 5))
    enemy_item_2 = game.create_sprite(5, randint(0, 5))
    enemy_item_3 = game.create_sprite(5, randint(0, 5))
    enemy_item_4 = game.create_sprite(5, randint(0, 5))
    basic.pause(250)
    enemy_item_1.change(LedSpriteProperty.X, -1)
    enemy_item_2.change(LedSpriteProperty.X, -1)
    enemy_item_3.change(LedSpriteProperty.X, -1)
    enemy_item_4.change(LedSpriteProperty.X, -1)
    basic.pause(250)
    enemy_item_1.change(LedSpriteProperty.X, -1)
    enemy_item_2.change(LedSpriteProperty.X, -1)
    enemy_item_3.change(LedSpriteProperty.X, -1)
    enemy_item_4.change(LedSpriteProperty.X, -1)
    basic.pause(250)
    enemy_item_1.change(LedSpriteProperty.X, -1)
    enemy_item_2.change(LedSpriteProperty.X, -1)
    enemy_item_3.change(LedSpriteProperty.X, -1)
    enemy_item_4.change(LedSpriteProperty.X, -1)
    basic.pause(250)
    enemy_item_1.change(LedSpriteProperty.X, -1)
    enemy_item_2.change(LedSpriteProperty.X, -1)
    enemy_item_3.change(LedSpriteProperty.X, -1)
    enemy_item_4.change(LedSpriteProperty.X, -1)
    basic.pause(250)
    enemy_item_1.delete()
    enemy_item_2.delete()
    enemy_item_3.delete()
    enemy_item_4.delete()

def on_forever():
    pass
basic.forever(on_forever)
if (item.isTouching(enemy_item_1)):
    item.delete()